feat(logs): add loki logs
OptimistikSAS/OIBus pull request #1306
Opened 2021-07-12 10:24 UTC by burgerni10

2021-07-12 13:46 UTC, burgerni10 commented
Working poc to send data to loki : 

![image](https://user-images.githubusercontent.com/28055217/125297769-d57e8380-e327-11eb-8986-7ed9effab7d3.png)

For now, I take the engineName, so if we set up loki logs, we need to rename the oibus engine so we can differentiate them.

To do : 
-basic auth
-send the logs to another OIBus
-get the logs from another OIBus and send them to loki (or to another OIBus ?)

2021-07-12 14:01 UTC, marouanehassanioptimistik requested changes

2021-07-12 14:01 UTC, marouanehassanioptimistik commented on src/engine/Logger.class.js
> +        host: lokiLog.host, // http://loki.igw.rd.optimistik.fr:3100
please remove this as it will spread our loki url

2021-07-12 15:07 UTC, jfhenon commented on src/south/ProtocolHandler.class.js
> +    this.logger.changeParameters(this.engineConfig.engineName, this.engineConfig.logParameters, logParameters)
maybe we should only send the engineConfig and it's up to the called function to pick engineName and logParameters.

2021-07-12 15:19 UTC, jfhenon reviewed
- Should the unique ID for Loki be a parameter at the Loki config level (making the OIBus engine name unique among all users may not be optimal).
- We don't solve the case of OIBus with no access to Internet. We should add the ability to forward Logs to another OIBus
- We may not need the OIBus alive anymore (or limit it to a regular log)

2021-07-13 07:59 UTC, burgerni10 commented
> * Should the unique ID for Loki be a parameter at the Loki config level (making the OIBus engine name unique among all users may not be optimal).
=> I don't see the point of the engineName anyway : should we juste have a 'loki-id' in the loki log level and remove the engine name from the config ?

> * We don't solve the case of OIBus with no access to Internet. We should add the ability to forward Logs to another OIBus
=> Will be done in a following PR

> * We may not need the OIBus alive anymore (or limit it to a regular log)
=> I agree that the Alive signal is OIAnalytics specific : people not using OIA must implement an endpoint for it. So for me it makes sense to remove the alive signal, once issue #1154 is done (it makes sense to do it now that winston-loki is almost implemented)

2021-07-13 21:30 UTC, jfhenon approved these changes

2021-07-15 06:16 UTC, marouanehassanioptimistik approved these changes

2021-07-16 12:47 UTC, merged