Cache and debounce
OptimistikSAS/OIBus pull request #1359
Opened 2021-08-21 11:22 UTC by jfhenon

Debounce: when a protocol receives many calls within a second, the engine is called multiple times (i.e. causing sqlite to be called inefficiently). This was causing an issue for a customer having several hundreds calls per second with a MQTT source. 
This PR proposes to group all calls within 300ms or below 250 values to be buffered and grouped into a single call to the engine. The 300ms/250 are now hard coded values but we may consider to expose them to the UI. 
Note that a single value will be delayed by 300ms before being sent to the engine.

2021-08-21 11:23 UTC, jfhenon commented
note that ADS tests have been impacted (calls were grouped) and has been adjusted.

2021-08-21 11:24 UTC, jfhenon commented
In the same PR, I fixed an issue with the cache that was checking the archive folder even if archive was not enabled.

2021-08-23 05:45 UTC, kukukk commented
I think it can lead to data loss. If OIBus is stoppped after the South calls `addValues` but before the buffer is flushed and `this.engine.addValues` is called. To avoid this we should save lastCompletedAt in the database only when we flush the buffer.

2021-08-23 06:55 UTC, burgerni10 requested changes

2021-08-23 06:55 UTC, burgerni10 commented on src/south/ProtocolHandler.class.js
> +      clearTimeout(this.bufferTimeout)
Need to check if bufferTimeout is null. Can happen if more than BUFFER_MAX values are retrieved at first call of this function

2021-08-23 06:55 UTC, burgerni10 commented on src/south/ProtocolHandler.class.js
> +    }
This method can be declared as private ProtocolHandler method so it won't create it at every addValues calls

2021-08-23 06:55 UTC, burgerni10 commented on src/south/ProtocolHandler.class.js
>    addValues(values) {
As Szabi mentionned, we can have data loss. Maybe we can pass the lastCompletedAt and the dataSourceId as parameters, store them in an array and update the database at the end of the flush to fix that

2021-08-23 06:55 UTC, burgerni10 commented on src/south/ProtocolHandler.class.js
> +      flush('max')
Shouldn't we await this method to avoir concurrency access to the buffer ?

2021-08-24 07:31 UTC, merged