feat(bulk-ui): Create user interface for bulk operations
OptimistikSAS/OIBus pull request #1458
Opened 2021-11-05 13:37 UTC by dezse97

The PR contains:
- create new bulk
- edit a bulk
- view the history configuration changes
- activate changes
- order bulks
- delete bulk
- duplicate bulk
- created a common reusable component for the points table

UI tests coming soon.

Please suggest design improvements:
<img width="1270" alt="Screenshot 2021-11-05 at 15 35 48" src="https://user-images.githubusercontent.com/16387138/140518755-f1bba711-e06f-4f39-aa73-c1f377f5da83.png">
<img width="1241" alt="Screenshot 2021-11-05 at 15 35 38" src="https://user-images.githubusercontent.com/16387138/140518767-7e6c087d-b437-4198-9c02-cf0df379fa64.png">
<img width="1305" alt="Screenshot 2021-11-05 at 15 35 09" src="https://user-images.githubusercontent.com/16387138/140518771-f32a5cbb-7b23-4f1f-b14e-31c3f7dffadf.png">

2021-11-05 13:42 UTC, burgerni10 commented
@jfhenon I wonder if the bulk menu should be accessible from the engine menu on the main page, under the 'Add South' item ?

@dezse97 : you can remove the breadcrumb on the Activation and Bulk pages.
On specific bulk, you can take the same sub-nav-bar than the south points configuration page with a "back" button. You can add the ongoing status inside the sub nav bar.

2021-11-05 14:18 UTC, dezse97 commented
> @jfhenon I wonder if the bulk menu should be accessible from the engine menu on the main page, under the 'Add South' item ?
> 
> @dezse97 : you can remove the breadcrumb on the Activation and Bulk pages. On specific bulk, you can take the same sub-nav-bar than the south points configuration page with a "back" button. You can add the ongoing status inside the sub nav bar.

@burgerni10 the second part of your comment is done. Updated the screenshots. The first part is doable as well, only decide how do you want :)

2021-11-08 14:59 UTC, jfhenon commented
> > @jfhenon I wonder if the bulk menu should be accessible from the engine menu on the main page, under the 'Add South' item ?

I would rather add it to the top toolbar.

2021-12-14 09:07 UTC, burgerni10 requested changes
Small changes, otherwise ok for me

2021-12-14 09:07 UTC, burgerni10 commented on src/client/services/apis.js
> +const activateHistoryConfig = () => putRequest('/historyQuery/config/activate')
url path should be history-query instead of historyQuery

2021-12-14 09:07 UTC, burgerni10 commented on src/client/index.jsx
> +              <Route exact path="/historyQuery/:id" element={<ConfigureHistoryQuery />} />
url path should be history-query instead of historyQuery

2021-12-14 09:07 UTC, burgerni10 commented on src/client/index.jsx
> +              <Route exact path="/historyQuery/:id" element={<ConfigureHistoryQuery />} />
To be adapted in the navigate call too

2021-12-14 09:07 UTC, burgerni10 commented on src/client/style/oi.css
> +.oi-add-bulk {
oi-add-history-query

2021-12-19 16:03 UTC, dezse97 commented
Changes are done @burgerni10. Can be merged from my side. Will continue on another branch

2021-12-20 08:15 UTC, burgerni10 approved these changes

2021-12-20 08:23 UTC, merged