opcua-ha-add-log-trace-for-investigation
OptimistikSAS/OIBus pull request #1815
Opened 2022-06-28 08:30 UTC by marouanehassanioptimistik

2022-06-28 08:32 UTC, jfhenon approved these changes

2022-06-28 20:45 UTC, burgerni10 approved these changes

2022-07-04 06:37 UTC, burgerni10 requested changes
@jfhenon  File deps/win/HdaAgent/app.publish/HdaAgent.exe can be deleted since it is not used and duplicated from deps/win/HdaAgent/HdaAgent.exe

2022-07-04 06:37 UTC, burgerni10 commented on deps/win/HdaAgent/HdaAgent.application
> -  <description asmv2:publisher="HdaAgent" asmv2:product="HdaAgent" xmlns="urn:schemas-microsoft-com:asm.v1" />
@jfhenon Can you change that to Optimistik ?

2022-07-04 06:37 UTC, burgerni10 commented on src/south/ProtocolHandler.class.js
> +      // eslint-disable-next-line max-len
Move this line to avoid linting errors

2022-07-06 12:55 UTC, jfhenon commented on src/south/OPCUA/OPCUA_HA/OPCUA_HA.class.js
> +      this.logger.trace(`No value for ${scanMode}`)
logger.warn?

2022-07-06 12:55 UTC, jfhenon commented on src/south/OPCUA/OPCUA_HA/OPCUA_HA.class.js
> +        this.logger.trace(`Received ${newerValues.length} new values for ${nodesToRead[i].pointId} among ${dataValue.length} values retrieved`)
logger.debug?

2022-07-07 07:00 UTC, merged