feat(file-cache): Endpoints to remove/retry file cache errors
OptimistikSAS/OIBus pull request #2077
Opened 2022-11-17 08:44 UTC by kukukk

2022-11-18 13:39 UTC, burgerni10 requested changes

2022-11-18 14:49 UTC, kukukk commented on src/web-server/routes/index.js
> +router.post('/file-cache/retryAllErrors', fileCacheController.retryAll)
retry-all and remove-all should be valid for a single north?
At the moment the implementation iterates over every active north.

2022-11-18 14:51 UTC, kukukk commented on src/service/utils.js
> +const asyncFilter = async (array, predicate) => {
I put it in utils.js to make generally available for the whole project as general async filter implementation. In this case the argument naming should be something general.

2022-11-18 15:21 UTC, burgerni10 commented on src/web-server/routes/index.js
> +router.post('/file-cache/retryAllErrors', fileCacheController.retryAll)
Yes, it should remove all cached for in this specific north

2022-11-18 15:23 UTC, burgerni10 commented on src/service/utils.js
> +const asyncFilter = async (array, predicate) => {
If this can be anything, maybe it's better to change the filename variable l 161 into something else, like element ?

2022-11-24 07:46 UTC, burgerni10 approved these changes

2022-11-24 09:05 UTC, merged