chore: refactor scan mode model, controller, services and tests
OptimistikSAS/OIBus pull request #3568
Opened 2024-09-10 09:52 UTC by burgerni10

2024-09-13 09:50 UTC, marouanehassanioptimistik requested changes
overall this is way better let's continue on this track some entities are more complex

2024-09-13 09:50 UTC, marouanehassanioptimistik commented on backend/src/service/scan-mode.service.ts
> +    }
this is weird this should already be the return type of the repo method, you can just proxy to the repo call

2024-09-13 09:50 UTC, marouanehassanioptimistik commented on backend/src/service/scan-mode.service.ts
> +    this.southCacheRepository.deleteAllByScanMode(scanModeId);
do you have a foreign key? if yes then maybe the order matters not sure but this require a closer look

2024-09-17 08:57 UTC, burgerni10 commented on backend/src/model/scan-mode.model.ts
> +};
TODO: place it in the service

2024-09-17 14:35 UTC, merged